### ISSUE TITLE
Handling of versions

### ISSUE THREAD

**Issue by cKNUSPeR** [NiCE-MSI/nectar_msi#1]
Hi, i get an error when trying to load the package due to the get_versions function missing from the ._version.py file. 
I was wondering if this just slipped out in the last commits.

My workaround was to change the import in the `__init__.py`  to `from ._version import __version__`, and that seems to work for me. 

But the package looks awesome and i can't wait to try it out.

**Comment by NiCE-MSI** [comment]
Thank you for letting me know. 
I have uploaded a new version (0.0.6) fixing this to pyp and here.
